title: {{ cookiecutter.project_name }}
description: {{ cookiecutter.description }}
author:
    name: RapidAgileSoftware
    twitter: {{ cookiecutter.twitter }}
email: {{ cookiecutter.email }}
lang: {{ cookiecutter.language }}
logo: tile.png

seo:
    type: Business

street: "{{ cookiecutter.street }}"
city: "{{ cookiecutter.city }}"
zip: "{{ cookiecutter.zip }}"
state: "{{ cookiecutter.state }}"
country: "{{ cookiecutter.country }}"
latitude: "{{ cookiecutter.latitude }}"
longitude: "{{ cookiecutter.longitude }}"

social:
  name: {{ cookiecutter.project_name }}
  links:

twitter:
    username: "{{ cookiecutter.twitter }}"

facebook:
    app_id: {{ cookiecutter.fb_app_id }}
    publisher: {{ cookiecutter.fb_publisher }}

google_site_verification: googleddcee30cf477c8ba
ga: {{ cookiecutter.ga }}

baseurl: ""
url: "{{ cookiecutter.domain }}"

exclude:

defaults:
  - scope:
      path: ""
    values:
      image: /files/facebook.png

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-seo-tag
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - package.json

# Github forced settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false

kramdown:
    input: GFM
    hard_wrap: false

# Sitemap

sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
